// <auto-generated />
using EnterpriceWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnterpriceWeb.Migrations
{
    [DbContext(typeof(AppDbConText))]
    partial class AppDbConTextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EnterpriceWeb.Models.Faculty", b =>
                {
                    b.Property<int>("f_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("f_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("f_id");

                    b.ToTable("faculties");
                });

            modelBuilder.Entity("EnterpriceWeb.Models.User", b =>
                {
                    b.Property<int>("us_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("f_id")
                        .HasColumnType("int");

                    b.Property<string>("us_end_year")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("us_gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("us_gmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("us_image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("us_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("us_password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("us_phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("us_start_year")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("us_id");

                    b.HasIndex("f_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("EnterpriceWeb.Models.User", b =>
                {
                    b.HasOne("EnterpriceWeb.Models.Faculty", "faculty")
                        .WithMany()
                        .HasForeignKey("f_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("faculty");
                });
#pragma warning restore 612, 618
        }
    }
}
